### ISSUE TITLE
Time in cals2pd

### ISSUE THREAD

**Issue by apoyet** [sterbini/cl2pd#11]
Hi, 

Could it be possible, using the cals2pd function to have, in a column, the UNIX Time also? It would be useful for the interpolation with numpy I think. I can of course translate the present timestamps to UNIX times, but it would be better to be as direct as possible since I'm quite sure UNIX Time is in CALS. 

Tell me what you think.

**Comment by sterbini** [comment]
Hi Axel,
the output of the cals2pd function is optimized for the minimum memory footprint. I think that few users need also the UNIX time so I would say that you can add the additional column in your postprocessing. 
Cheers,
G.

**Comment by apoyet** [comment]
Ok, I’ll do it then :)

Cheers,



Axel

On 11 Jun 2018 at 11:31 +0200, sterbini <notifications@github.com>, wrote:

Hi Axel,
the output of the cals2pd function is optimized for the minimum memory footprint. I think that few users need also the UNIX time so I would say that you can add the additional column in your postprocessing.
Cheers,
G.

**Comment by sterbini** [comment]
I close the issue then.
