### ISSUE TITLE
Corrupt data

### ISSUE THREAD

**Issue by Kurburis** [sterbini/cl2pd#22]
Suad: Looks like some of the fills are missing. Calling functions on them causes exceptions ( for example importData.LHCFillsByNumber(6578)). 

Maybe add some exception handling that in cases of missing fills function returns an empty data frame.

**Comment by sterbini** [comment]
Interesting. Thanks! I can reproduce the problem. I will have a look.

**Comment by Kurburis** [comment]
Also some fills are completely empty (for example importData.LHCFillsByNumber(6734))

**Comment by sterbini** [comment]
This is due to the fact that the fill is not found.
Have a look to 
http://acc-stats.web.cern.ch/acc-stats/#lhc/super-table

**Comment by sterbini** [comment]
Indeed the problem occurred when the FILL has not beam modes. Now it is fixed.
