### ISSUE TITLE
tfs2pd output

### ISSUE THREAD

**Issue by apoyet** [sterbini/cl2pd#9]
Hi, 

The tfs2pd function returns only the globalDF from MAD-X. Is it definitive? If yes, I will either write a short function in order to extract the opticsDF from that, or adapt the code in the notebook to stick to this approach. 

Nonetheless, my suggestion is to include a getOptics function returning both opticsDF and globalDF (as the previous approach) and therefore use the _tfs2pd notation in order not to expose it. 

Tell me what you think so I can modify my fork, or implement that in my own toolbox.

**Comment by sterbini** [comment]
I propose to leave the output at it is. I will generalize the function to accept a list of file names.

**Comment by sterbini** [comment]
Done.
